name: Has Privileged Access
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  print:
    name: Detect Author
    runs-on: ubuntu-latest
    steps:
      - name: Only Allow Members
        uses: ./.github/actions/only-allow-members

      - name: Runs if local PR or dependabot
        run: echo "Passes"
