name: Print Pull Request Event
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  print:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq '.'
