name: Print Pull Request Target Event
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  print:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq '.'
